//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kros.MsAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kros.MsAccess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided connection string is not a connection string for Microsoft Access database. Supported providers are Microsoft.ACE.OLEDB and Microsoft.Jet.OLEDB..
        /// </summary>
        internal static string ConnectionStringIsNotMsAccess {
            get {
                return ResourceManager.GetString("ConnectionStringIsNotMsAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cannot be inserted. Data file does not exist: {0}.
        /// </summary>
        internal static string CsvFileDoesNotExist {
            get {
                return ResourceManager.GetString("CsvFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Access provider &quot;{0}&quot; is not installed..
        /// </summary>
        internal static string ProviderNotInstaller {
            get {
                return ResourceManager.GetString("ProviderNotInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [IdStore] (
        ///	[TableName] char(100) NOT NULL,
        ///	[LastId] int NOT NULL
        ///);
        ///
        ///CREATE UNIQUE INDEX  [PK_IdStore] ON [IdStore] ([TableName] ASC) WITH PRIMARY;
        ///.
        /// </summary>
        internal static string SqlIdGeneratorTableScript {
            get {
                return ResourceManager.GetString("SqlIdGeneratorTableScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown data type for CSV file. Data type: {0}, value: {1}.
        /// </summary>
        internal static string UnknownDataTypeForCsv {
            get {
                return ResourceManager.GetString("UnknownDataTypeForCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported data type for Microsoft Access bulk insert: OleDbType.{0}.
        /// </summary>
        internal static string UnsupportedBulkInsertDataType {
            get {
                return ResourceManager.GetString("UnsupportedBulkInsertDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection type is not supported. The connection must be of type OleDbConnection and must have correct provider, Microsoft.ACE.OLEDB or Microsoft.Jet.OLEDB..
        /// </summary>
        internal static string UnsupportedConnectionType {
            get {
                return ResourceManager.GetString("UnsupportedConnectionType", resourceCulture);
            }
        }
    }
}
