//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kros.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kros.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota parametra musí byť {0}, ale skutočná hodnota je {1}..
        /// </summary>
        internal static string Check_Equal {
            get {
                return ResourceManager.GetString("Check_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota parametra musí byť väčšia alebo rovná {0}, ale skutočná hodnota je {1}..
        /// </summary>
        internal static string Check_GreaterOrEqualThan {
            get {
                return ResourceManager.GetString("Check_GreaterOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota parametra musí byť väčšia ako {0}, ale skutočná hodnota je {1}..
        /// </summary>
        internal static string Check_GreaterThan {
            get {
                return ResourceManager.GetString("Check_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota &quot;{0}&quot; musí byť zo zoznamu hodnôt &quot;{1}&quot;..
        /// </summary>
        internal static string Check_IsInListDefaultMessage {
            get {
                return ResourceManager.GetString("Check_IsInListDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota &quot;{0}&quot; nesmie byť zo zoznamu hodnôt &quot;{1}&quot;..
        /// </summary>
        internal static string Check_IsNotInListDefaultMessage {
            get {
                return ResourceManager.GetString("Check_IsNotInListDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter nemôže byť typu {0}..
        /// </summary>
        internal static string Check_IsNotOfType {
            get {
                return ResourceManager.GetString("Check_IsNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter nie je požadovaného typu. Požadovaný typ: {0}. Typ parametra: {1}..
        /// </summary>
        internal static string Check_IsOfType {
            get {
                return ResourceManager.GetString("Check_IsOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota parametra musí byť menšia alebo rovná {0}, ale skutočná hodnota je {1}..
        /// </summary>
        internal static string Check_LessOrEqualThan {
            get {
                return ResourceManager.GetString("Check_LessOrEqualThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota parametra musí byť menšia ako {0}, ale skutočná hodnota je {1}..
        /// </summary>
        internal static string Check_LessThan {
            get {
                return ResourceManager.GetString("Check_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prázdny GUID nie je povolený..
        /// </summary>
        internal static string Check_NotEmptyGuid {
            get {
                return ResourceManager.GetString("Check_NotEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota parametrov nesmie byť rovnaká {0}..
        /// </summary>
        internal static string Check_NotEqual {
            get {
                return ResourceManager.GetString("Check_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota nemôže byť null..
        /// </summary>
        internal static string Check_NotNull {
            get {
                return ResourceManager.GetString("Check_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reťazec nemôže byť null, alebo prázdny..
        /// </summary>
        internal static string Check_StringNotNullOrEmpty {
            get {
                return ResourceManager.GetString("Check_StringNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reťazec nemôže byť null, prázdny, ani zložený iba z bielych znakov..
        /// </summary>
        internal static string Check_StringNotNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Check_StringNotNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodporovaný typ pripojenia na databázu: {0}.
        /// </summary>
        internal static string DatabaseSchemaCache_UnsupportedDatabaseType {
            get {
                return ResourceManager.GetString("DatabaseSchemaCache_UnsupportedDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodporovaný typ spojenia na databázu..
        /// </summary>
        internal static string DatabaseSchemaLoader_UnsupportedConnectionType {
            get {
                return ResourceManager.GetString("DatabaseSchemaLoader_UnsupportedConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie je možné zmeniť názov indexu, ak je v zozname indexov tabuľky. Tento index patrí tabuľke &quot;{0}&quot;..
        /// </summary>
        internal static string IndexSchema_CannotChangeIndexNameWhenBelongsToTable {
            get {
                return ResourceManager.GetString("IndexSchema_CannotChangeIndexNameWhenBelongsToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stĺpec &quot;{0}&quot; nie je možné pridať indexu &quot;{1}&quot;, pretože už patrí indexu &quot;{2}&quot;..
        /// </summary>
        internal static string Schema_ColumnBelongsToAnotherIndex {
            get {
                return ResourceManager.GetString("Schema_ColumnBelongsToAnotherIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stĺpec &quot;{0}&quot; nie je možné pridať tabuľke &quot;{1}&quot;, pretože už patrí tabuľke &quot;{2}&quot;..
        /// </summary>
        internal static string Schema_ColumnBelongsToAnotherTable {
            get {
                return ResourceManager.GetString("Schema_ColumnBelongsToAnotherTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cudzí kľúč &quot;{0}&quot; nie je možné pridať tabuľke &quot;{1}&quot;, pretože už patrí tabuľke &quot;{2}&quot;..
        /// </summary>
        internal static string Schema_ForeignKeyBelongsToAnotherTable {
            get {
                return ResourceManager.GetString("Schema_ForeignKeyBelongsToAnotherTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index &quot;{0}&quot; nie je možné pridať tabuľke &quot;{1}&quot;, pretože už patrí tabuľke &quot;{2}&quot;..
        /// </summary>
        internal static string Schema_IndexBelongsToAnotherTable {
            get {
                return ResourceManager.GetString("Schema_IndexBelongsToAnotherTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabuľku &quot;{0}&quot; nie je možné pridať databáze &quot;{1}&quot;, pretože už patrí databáze &quot;{2}&quot;..
        /// </summary>
        internal static string Schema_TableBelongsToAnotherDatabase {
            get {
                return ResourceManager.GetString("Schema_TableBelongsToAnotherDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodporovaný typ pripojenia na databázu. Podporované pripojenia na databázy sú: {0}.
        /// </summary>
        internal static string SchemaCacheKeyGenerator_UnsupportedConnectionType {
            get {
                return ResourceManager.GetString("SchemaCacheKeyGenerator_UnsupportedConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre načítanie schémy je nutné, aby spojenie na databázu malo špecifikovanú konkrétnu databázu (Initial Catalog)..
        /// </summary>
        internal static string SqlServerSchemaLoader_NoInitialCatalog {
            get {
                return ResourceManager.GetString("SqlServerSchemaLoader_NoInitialCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodporovaný typ spojenia na databázu. Spojenie musí byť typu SqlConnection..
        /// </summary>
        internal static string SqlServerSchemaLoader_UnsupportedConnectionType {
            get {
                return ResourceManager.GetString("SqlServerSchemaLoader_UnsupportedConnectionType", resourceCulture);
            }
        }
    }
}
